-- Необязательный сид: переносит сотрудников и смены недели 15-21.06.2026
-- из исходного файла Excel. Выполните ПОСЛЕ schema.sql, если хотите
-- начать не с пустой базы.

insert into employees (fio, stop) values ('Айсигалиев Сергей', 'Мегаполис') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Алипов Григорий', 'Своим ходом') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Алиева Айтен', 'Мегаполис') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Алексеев Александр', 'Своим ходом') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Алексеева Людмила', 'Своим ходом') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Алкаева Лариса', 'Мегаполис') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Байрамова Анастасия', 'Щорса') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Батищева Елизавета', 'Щорса') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Беспаль Ксения', 'Дагестанская') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Варасьян Дина', 'Самоцветный бульвар') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Варасьян Саро', 'Самоцветный бульвар') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Горбачева Екатерина', 'Щорса') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Демченко Елена', 'Мегаполис') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Демченко Вероника', 'Мегаполис') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Доника Кристина', 'Мегаполис') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Епифанов Антон', 'Мегаполис') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Зиганшина Альбина', 'ДК Химмаш') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Иванова Майя', 'Своим ходом') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Иломанова Алёна', 'ДК Химмаш') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Иломанов Никита', 'ДК Химмаш') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Качалова Анастасия', 'Мегаполис') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Коршунов Александр', 'Своим ходом') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Коршунова Светлана', 'Своим ходом') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Курапова София', 'Мегаполис') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Летемина Татьяна', 'Своим ходом') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Логинова Надежда', 'Дирижабль') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Мануйло Игорь', 'Дирижабль') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Мироненко Любовь', 'Пос. Лосиный') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Михайлова Кристина', 'Шварца') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Нажмутдинова Дарья', 'Своим ходом') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Невьянцева Анна', 'Мегаполис') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Николаева Анастасия', 'Мегаполис') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Николаева Дарья', 'Мегаполис') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Ноговицина Анна', 'Мегаполис') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Онегова Полина', 'Мегаполис') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Полуэктов Олег', 'Самоцветный бульвар') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Провкова Ирина', 'Новоуральск (ж/д вокзал)') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Савина Анастасия', 'Мегаполис') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Сарыглар Малина', 'Мегаполис') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Сат Хенче', 'Дирижабль') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Салхинашвили Владислав', 'Шварца') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Силина Валентина', 'Новоуральск (ж/д вокзал)') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Сыропятова Лада', 'Шварца') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Толмачёва Юлия', 'Мегаполис') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Хамидуллина Роза', 'ДК Химмаш') on conflict (fio) do nothing;
insert into employees (fio, stop) values ('Ячменёва Наталья', 'Не указано') on conflict (fio) do nothing;

insert into shifts (employee_id, work_date) select id, '2026-06-16' from employees where fio = 'Алипов Григорий' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-17' from employees where fio = 'Алипов Григорий' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-19' from employees where fio = 'Алипов Григорий' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-17' from employees where fio = 'Байрамова Анастасия' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-21' from employees where fio = 'Байрамова Анастасия' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-17' from employees where fio = 'Горбачева Екатерина' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-21' from employees where fio = 'Горбачева Екатерина' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-15' from employees where fio = 'Зиганшина Альбина' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-17' from employees where fio = 'Зиганшина Альбина' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-18' from employees where fio = 'Зиганшина Альбина' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-15' from employees where fio = 'Иломанова Алёна' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-17' from employees where fio = 'Иломанова Алёна' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-19' from employees where fio = 'Иломанова Алёна' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-15' from employees where fio = 'Иломанов Никита' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-17' from employees where fio = 'Иломанов Никита' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-19' from employees where fio = 'Иломанов Никита' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-20' from employees where fio = 'Летемина Татьяна' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-21' from employees where fio = 'Летемина Татьяна' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-15' from employees where fio = 'Мироненко Любовь' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-17' from employees where fio = 'Мироненко Любовь' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-17' from employees where fio = 'Нажмутдинова Дарья' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-18' from employees where fio = 'Нажмутдинова Дарья' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-15' from employees where fio = 'Ноговицина Анна' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-19' from employees where fio = 'Ноговицина Анна' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-15' from employees where fio = 'Полуэктов Олег' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-20' from employees where fio = 'Полуэктов Олег' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-21' from employees where fio = 'Полуэктов Олег' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-15' from employees where fio = 'Савина Анастасия' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-16' from employees where fio = 'Савина Анастасия' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-17' from employees where fio = 'Савина Анастасия' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-18' from employees where fio = 'Савина Анастасия' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-19' from employees where fio = 'Савина Анастасия' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-20' from employees where fio = 'Савина Анастасия' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-21' from employees where fio = 'Савина Анастасия' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-17' from employees where fio = 'Салхинашвили Владислав' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-19' from employees where fio = 'Салхинашвили Владислав' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-15' from employees where fio = 'Сыропятова Лада' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-19' from employees where fio = 'Сыропятова Лада' on conflict (employee_id, work_date) do nothing;
insert into shifts (employee_id, work_date) select id, '2026-06-21' from employees where fio = 'Сыропятова Лада' on conflict (employee_id, work_date) do nothing;
